name: Firmware Build CI

on:
  push:
    branches: 
      - 'main'
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Installing platformio
      run: pip3 install -U platformio
      
    - name: Installing project deppendencies
      run: pio lib install

    - name: Building a firmware for ESP32
      run: pio run
